service: basics
frameworkVersion: '3'
app: aws-node

plugins:
  - serverless-plugin-typescript
  - serverless-iam-roles-per-function
provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
environment:
  keys: ${self:custom:Test_Key}
  myStage: ${sls.stage}
functions:
  hello: ${file(resources/hello.yml):hello}
    
custom:
  Test_Key: "abcdefgh"